# animaciones 
animations {
    enabled = true

    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.35, 0.95
    bezier = easeOutBack, 0.34, 1.56, 0.64, 1
    bezier = linear, 0, 0, 1, 1

    animation = windows, 1, 5, easeOutBack, slide
    animation = windowsOut, 1, 4, easeOutQuint, slide
    animation = windowsMove, 1, 4, easeInOutCubic
    animation = fade, 1, 4, easeOutQuint
    animation = fadeOut, 1, 4, easeOutQuint
    animation = border, 1, 6, linear
    animation = borderangle, 1, 8, linear, loop
    animation = workspaces, 1, 5, easeOutQuint, slide
    animation = specialWorkspace, 1, 5, easeOutBack, slidevert
}
# blur
 decoration {
    blur {
        enabled = true
        size = 8
        passes = 3
        noise = 0.02
        contrast = 0.9
        brightness = 0.8
        vibrancy = 0.2
        new_optimizations = true
        xray = false
    }
}
# borders
general {
    border_size = 2
    gaps_in = 5
    gaps_out = 10
    col.active_border = rgba(D4AF37ff) rgba(8E0E18ff) 45deg
    col.inactive_border = rgba(2A2A2Aff)
}

decoration {
    rounding = 12
}