# ==========================
# core no ronpas nada ggs
# ==========================
source = ~/.config/hypr/core/variables.conf
source = ~/.config/hypr/core/env.conf
source = ~/.config/hypr/core/startup.conf
source = ~/.config/hypr/core/autostart.conf
source = ~/.config/hypr/core/cursor.conf
source = ~/.config/hypr/core/misc.conf
source = ~/.config/hypr/core/input.conf
source = ~/.config/hypr/core/monitors.conf


# ==========================
# decoracioon de las ventanas
# ==========================
source = ~/.config/hypr/alltheme.conf

# ==========================
# cosas que hay que crear par que funcione bien las cosas
# ==========================
source = ~/.config/hypr/rules/windows.conf
source = ~/.config/hypr/rules/layers.conf
source = ~/.config/hypr/rules/opacity.conf
source = ~/.config/hypr/rules/workspace.conf
# ==========================
# Keybinds
# ==========================
source = ~/.config/hypr/allkeys.conf
#=======================
# configuraciones temporales
#=======================
decoration {
    rounding = 12

    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
    }
}
