windowrule = match:class ^(zen)$, opacity 0.85 0.75
windowrule = match:class ^(steam)$, opacity 0.85 0.75
windowrule = match:class ^(discord)$, opacity 0.85 0.75
windowrule = match:class ^(spotify)$, opacity 0.85 0.75