# zen
windowrule = match:class ^(zen)$, float on
windowrule = match:class ^(zen)$, size 1200 800
# steam
windowrule = match:class ^(steam_app_.*)$, content game
windowrule = match:content game, immediate on
