exec-once = awww-daemon
exec-once = ~/.config/hypr/scripts/wallpaper.sh
# waybar
exec-once = waybar -c ~/.config/hypr/waybar/config.jsonc -s ~/.config/hypr/waybar/style.css
# wallpaper
exec-once = waywallen-layer-shell --socket /run/user/1000/.flatpak/org.waywallen.waywallen/xdg-run/waywallen/display.sock
exec-once = sleep 2 && flatpak run org.waywallen.waywallen